// Code generated by scripts/gen-width-tables.py; DO NOT EDIT.

package vt

// tablesUnicodeVersion is the UCD release the width tables in width.go were
// generated from.
const tablesUnicodeVersion = "17.0.0"
