// Tier 3 — mechanical all-codes display conformance via a real headless
// Chromium (Playwright drives it over the Chrome DevTools Protocol). Instead of
// sampling screenshot pixels (fragile, font-dependent), this renders the
// ENGINE's actual wire output for EVERY SGR display code and DUMPS each cell's
// getComputedStyle over CDP, then asserts each dump against the SPEC.
//
// The fixture pair is generated by terminal/render_golden_test.go
// TestRenderGoldenAllCodes:
//   - render-golden/all-codes.bin           the engine's real wire frame
//   - render-golden/all-codes.manifest.json the layout (which SGR each row
//                                            carries) — "what was fed", never
//                                            the expected output.
// Expectations are derived HERE from the published standards (spec-colors.ts +
// the ANSI/CSS attribute mapping), not copied from render.ts. A mismatch is a
// finding.
//
// Fresh headless Chromium per the chromium-sidecar steering doc (the shared
// sidecar is debug-only). Out of the vitest battery; run `npm run test:e2e`.
import { test, expect } from "@playwright/test";
import * as esbuild from "esbuild";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { standard256, rgb } from "../src/test-helpers/spec-colors.js";

const webDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const goldenDir = path.resolve(webDir, "..", "render-golden");

// esbuild resolves ESM `.js` import specifiers to their `.ts` sources so
// render.ts (which imports "./store.js" etc.) bundles for the browser.
const jsToTs = {
  name: "js-to-ts",
  setup(build: esbuild.PluginBuild) {
    build.onResolve({ filter: /\.js$/ }, (args) => {
      if (!args.path.startsWith(".")) {
        return null;
      }
      const tsPath = path.resolve(args.resolveDir, args.path.replace(/\.js$/, ".ts"));
      return fs.existsSync(tsPath) ? { path: tsPath } : null;
    });
  },
};

// Bundle the real renderer AND the real wire decoder into one IIFE global so the
// page decodes the engine's actual bytes and renders them with production code.
async function bundleEngine(): Promise<string> {
  const result = await esbuild.build({
    stdin: {
      contents: `export * as render from "./src/render.js";
export { decodeWireBinary } from "./src/wire-binary.js";`,
      resolveDir: webDir,
      loader: "ts",
    },
    bundle: true,
    format: "iife",
    globalName: "WTE",
    write: false,
    plugins: [jsToTs],
  });
  return result.outputFiles[0]!.text;
}

// The harness mirrors web-terminal-ui's default CSS vars so inverse-on-default
// resolves to concrete colors the computed-style dump can read: --text #dddee1
// (rgb(221,222,225)), --bg #000000 (rgb(0,0,0)).
const HARNESS = `<!doctype html><html><head><meta charset="utf-8"><style>
  :root { --bg: #000000; --text: #dddee1; }
  html, body { margin: 0; padding: 0; background: var(--bg); }
  #wrap { font: 16px/1.25 "DejaVu Sans Mono", "Liberation Mono", monospace;
          color: var(--text); background: var(--bg); padding: 4px; width: 400px; }
  #out { white-space: pre; }
</style></head><body>
  <div id="wrap"><div id="out"></div></div>
</body></html>`;

// One row's dumped computed style (the styled first span carrying the glyph).
interface CellDump {
  color: string;
  backgroundColor: string;
  fontWeight: string;
  fontStyle: string;
  textDecorationLine: string;
  textDecorationStyle: string;
  textDecorationColor: string;
  opacity: string;
  visibility: string;
  className: string;
}

interface ManifestEntry {
  row: number;
  kind: string;
  code: number;
  r: number;
  g: number;
  b: number;
}

// parseRGB turns a computed "rgb(r, g, b)" / "rgba(r, g, b, a)" into 0xRRGGBB,
// or null if the string isn't an opaque rgb color.
function parseRGB(s: string): number | null {
  const m = /^rgba?\((\d+),\s*(\d+),\s*(\d+)/.exec(s);
  if (!m) {
    return null;
  }
  return (Number(m[1]) << 16) | (Number(m[2]) << 8) | Number(m[3]);
}

function hexStr(v: number): string {
  return "#" + (v >>> 0).toString(16).padStart(6, "0");
}

test.describe("all-codes display conformance (engine wire → real chromium → computed style)", () => {
  test("every SGR display code renders to its spec computed style", async ({ page }) => {
    const bundle = await bundleEngine();
    const manifest = JSON.parse(
      fs.readFileSync(path.join(goldenDir, "all-codes.manifest.json"), "utf8"),
    ) as ManifestEntry[];
    const frameBytes = Array.from(fs.readFileSync(path.join(goldenDir, "all-codes.bin")));

    await page.setContent(HARNESS);
    await page.addScriptTag({ content: bundle });

    // Decode the engine's real frame and render it with production render.ts.
    await page.evaluate((bytes: number[]) => {
      const buf = new Uint8Array(bytes).buffer;
      const msg = WTE.decodeWireBinary(buf);
      if (!msg || msg.type !== "screen") {
        throw new Error("fixture did not decode as a screen frame");
      }
      const out = document.getElementById("out")!;
      const wrap = document.getElementById("wrap")!;
      WTE.render.init({ output: out, termWrap: wrap });
      WTE.render.updateFontMetrics();
      WTE.render.handleScreen(msg);
    }, frameBytes);
    // render.ts batches DOM writes; let the flush complete before dumping.
    await page.waitForTimeout(250);

    // Dump the computed style of each row's first NON-BLANK span (the styled
    // glyph "X"; the blank fill after it carries default style).
    const dumps = await page.evaluate((): CellDump[] => {
      const out = document.getElementById("out")!;
      const result: CellDump[] = [];
      // Row order is preserved so result[i] corresponds to manifest row i.
      for (const rowEl of Array.from(out.children)) {
        const spans = Array.from(rowEl.children) as HTMLElement[];
        const span = spans.find((s) => (s.textContent ?? "").trim().length > 0) ?? spans[0];
        if (!span) {
          result.push(null as unknown as CellDump);
          continue;
        }
        const cs = getComputedStyle(span);
        result.push({
          color: cs.color,
          backgroundColor: cs.backgroundColor,
          fontWeight: cs.fontWeight,
          fontStyle: cs.fontStyle,
          textDecorationLine: cs.textDecorationLine,
          textDecorationStyle: cs.textDecorationStyle,
          textDecorationColor: cs.textDecorationColor,
          opacity: cs.opacity,
          visibility: cs.visibility,
          className: span.className,
        });
      }
      return result;
    });

    // --- Per-code spec analysis. expect.soft so a single run reports EVERY
    // deviation across all 300+ codes, not just the first. ---
    const basicFg = new Map<number, number>(); // SGR code -> rendered 0xRRGGBB
    const idx256Fg = new Map<number, number>(); // 256-index (0..15) -> 0xRRGGBB
    const basicBg = new Map<number, number>(); // SGR code -> 0xRRGGBB

    for (const e of manifest) {
      const d = dumps[e.row];
      const at = `row ${e.row} ${e.kind} code=${e.code}`;
      expect(d, `${at}: must render a styled span`).toBeTruthy();
      if (!d) {
        continue;
      }
      switch (e.kind) {
        case "attr":
          checkAttr(e.code, d, at);
          break;
        case "basicFg": {
          const got = parseRGB(d.color);
          expect.soft(got, `${at}: fg must be an opaque rgb`).not.toBeNull();
          if (got !== null) {
            basicFg.set(e.code, got);
          }
          break;
        }
        case "basicBg": {
          const got = parseRGB(d.backgroundColor);
          expect.soft(got, `${at}: bg must be an opaque rgb`).not.toBeNull();
          if (got !== null) {
            basicBg.set(e.code, got);
          }
          break;
        }
        case "color256Fg": {
          const got = parseRGB(d.color);
          if (e.code >= 16) {
            // Cube (16-231) + grayscale (232-255): exact standard formula.
            expect
              .soft(got === null ? got : hexStr(got), `${at}: 256-color must equal the spec RGB`)
              .toBe(hexStr(standard256(e.code)));
          } else if (got !== null) {
            // 0-15 are terminal-defined; checked for consistency below.
            idx256Fg.set(e.code, got);
          }
          break;
        }
        case "truecolorFg":
          expect
            .soft(
              parseRGBOrNull(d.color),
              `${at}: truecolor fg must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        case "truecolorBg":
          expect
            .soft(
              parseRGBOrNull(d.backgroundColor),
              `${at}: truecolor bg must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        case "ulColor":
          expect
            .soft(d.textDecorationLine, `${at}: underline must be present`)
            .toContain("underline");
          expect
            .soft(
              parseRGBOrNull(d.textDecorationColor),
              `${at}: underline color must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        default:
          throw new Error(`unknown manifest kind ${e.kind}`);
      }
    }

    // --- Palette consistency (ANSI: SGR 30+n / 90+n, SGR 38;5;n<16, and the
    // background SGR 40+n / 100+n all address the SAME 16 palette slots, so they
    // must render identical RGB). This pins internal consistency without pinning
    // the terminal-defined RGB choice. ---
    for (let n = 0; n < 8; n++) {
      assertSameSlot(basicFg.get(30 + n), idx256Fg.get(n), `SGR 3${n} == SGR 38;5;${n}`);
      assertSameSlot(basicFg.get(90 + n), idx256Fg.get(8 + n), `SGR 9${n} == SGR 38;5;${8 + n}`);
      assertSameSlot(basicBg.get(40 + n), basicFg.get(30 + n), `SGR 4${n} bg == SGR 3${n} fg`);
      assertSameSlot(basicBg.get(100 + n), basicFg.get(90 + n), `SGR 10${n} bg == SGR 9${n} fg`);
    }
    // The 16 base colors must be mutually distinct (a collapsed palette is a bug).
    const distinct = new Set([...basicFg.values()]);
    expect.soft(distinct.size, "the 16 base colors must be mutually distinct").toBe(16);
  });
});

// parseRGBOrNull is parseRGB but typed for the toBe(number) assertions above.
function parseRGBOrNull(s: string): number | null {
  return parseRGB(s);
}

function assertSameSlot(a: number | undefined, b: number | undefined, why: string): void {
  expect.soft(a, `${why}: left slot must render`).not.toBeUndefined();
  expect.soft(b, `${why}: right slot must render`).not.toBeUndefined();
  if (a !== undefined && b !== undefined) {
    expect.soft(hexStr(a), `${why}: same palette slot must render identical RGB`).toBe(hexStr(b));
  }
}

// checkAttr asserts an SGR text-attribute row against the CSS the standard
// prescribes (bold weight, italic style, decoration lines, faint intensity,
// concealment, blink).
function checkAttr(code: number, d: CellDump, at: string): void {
  switch (code) {
    case 1: // bold
      expect.soft(Number(d.fontWeight), `${at}: bold must be >= 700`).toBeGreaterThanOrEqual(700);
      break;
    case 2: // faint / dim — reduced intensity
      expect.soft(Number(d.opacity), `${at}: faint must reduce opacity`).toBeLessThan(1);
      break;
    case 3: // italic
      expect.soft(d.fontStyle, `${at}: italic`).toBe("italic");
      break;
    case 4: // underline
      expect.soft(d.textDecorationLine, `${at}: underline`).toContain("underline");
      break;
    case 5: // blink
      expect.soft(d.className, `${at}: blink must add the blink class`).toContain("term-blink");
      break;
    case 7: // inverse over defaults: fg<->bg swap => text bg-on-fg
      expect.soft(parseRGB(d.color), `${at}: inverse text takes the bg color`).toBe(0x000000);
      expect
        .soft(parseRGB(d.backgroundColor), `${at}: inverse fill takes the fg color`)
        .toBe(0xdddee1);
      break;
    case 8: // conceal / hidden
      expect.soft(d.visibility, `${at}: hidden must be invisible`).toBe("hidden");
      break;
    case 9: // strikethrough
      expect.soft(d.textDecorationLine, `${at}: strike`).toContain("line-through");
      break;
    case 21: // double underline
      expect
        .soft(d.textDecorationLine, `${at}: double underline is an underline`)
        .toContain("underline");
      expect.soft(d.textDecorationStyle, `${at}: double underline style`).toBe("double");
      break;
    case 53: // overline
      expect.soft(d.textDecorationLine, `${at}: overline`).toContain("overline");
      break;
    default:
      throw new Error(`unhandled attr code ${code}`);
  }
}

// WTE is the esbuild IIFE global injected via addScriptTag.
declare const WTE: {
  render: {
    init: (opts: { output: unknown; termWrap: unknown; onCursorMove?: () => void }) => void;
    updateFontMetrics: () => void;
    handleScreen: (msg: unknown) => void;
  };
  decodeWireBinary: (buf: ArrayBuffer) => { type: string } | null;
};
