// Tier 3 — mechanical all-codes display conformance via a real headless
// Chromium (Playwright drives it over the Chrome DevTools Protocol). Instead of
// sampling screenshot pixels (fragile, font-dependent), this renders the
// ENGINE's actual wire output for EVERY SGR display code and DUMPS each cell's
// getComputedStyle over CDP, then asserts each dump against the SPEC.
//
// The fixture pair is generated by terminal/render_golden_test.go
// TestRenderGoldenAllCodes:
//   - render-golden/all-codes.bin           the engine's real wire frame
//   - render-golden/all-codes.manifest.json the layout (which SGR each row
//                                            carries) — "what was fed", never
//                                            the expected output.
// Expectations are derived HERE from the published standards (spec-colors.ts +
// the ANSI/CSS attribute mapping), not copied from render.ts. A mismatch is a
// finding.
//
// Fresh headless Chromium per the chromium-sidecar steering doc (the shared
// sidecar is debug-only). Out of the vitest battery; run `npm run test:e2e`.
import { test, expect } from "@playwright/test";
import { standard256, rgb, vga16 } from "../src/test-helpers/spec-colors.js";
import { bundleEngine, HARNESS, readGolden, frameBytesArray, waitForRows } from "./e2e-harness.js";

// One row's dumped computed style (the styled first span carrying the glyph).
interface CellDump {
  color: string;
  backgroundColor: string;
  fontWeight: string;
  fontStyle: string;
  textDecorationLine: string;
  textDecorationStyle: string;
  textDecorationColor: string;
  opacity: string;
  visibility: string;
  className: string;
}

interface ManifestEntry {
  row: number;
  kind: string;
  code: number;
  r: number;
  g: number;
  b: number;
}

// parseRGB turns a computed "rgb(r, g, b)" / "rgba(r, g, b, a)" into 0xRRGGBB,
// or null if the string isn't an opaque rgb color.
function parseRGB(s: string): number | null {
  const m = /^rgba?\((\d+),\s*(\d+),\s*(\d+)/.exec(s);
  if (!m) {
    return null;
  }
  return (Number(m[1]) << 16) | (Number(m[2]) << 8) | Number(m[3]);
}

function hexStr(v: number): string {
  return "#" + (v >>> 0).toString(16).padStart(6, "0");
}

test.describe("all-codes display conformance (engine wire → real chromium → computed style)", () => {
  test("every SGR display code renders to its spec computed style", async ({ page }) => {
    const bundle = await bundleEngine();
    const manifest = JSON.parse(
      readGolden("all-codes.manifest.json").toString("utf8"),
    ) as ManifestEntry[];
    const frameBytes = frameBytesArray("all-codes.bin");

    await page.setContent(HARNESS);
    await page.addScriptTag({ content: bundle });

    // Decode the engine's real frame and render it with production render.ts.
    await page.evaluate((bytes: number[]) => {
      const buf = new Uint8Array(bytes).buffer;
      const msg = WTE.decodeWireBinary(buf);
      if (!msg || msg.type !== "screen") {
        throw new Error("fixture did not decode as a screen frame");
      }
      const out = document.getElementById("out")!;
      const wrap = document.getElementById("wrap")!;
      WTE.render.init({ output: out, termWrap: wrap });
      WTE.render.updateFontMetrics();
      WTE.render.handleScreen(msg);
    }, frameBytes);
    // render.ts batches DOM writes across rAF frames; wait until every
    // manifest row's div exists (deterministic, replaces a fixed sleep).
    await waitForRows(page, manifest.length);

    // Dump the computed style of every NON-BLANK span per row, in DOM order.
    // Single-glyph rows use span [0]; the on->off rows (attrOff / defaultColor /
    // ulStyle 4:0) use [0] (the ON/set glyph) and [1] (the OFF/default glyph).
    const dumps = await page.evaluate((): CellDump[][] => {
      const out = document.getElementById("out")!;
      const dumpSpan = (span: HTMLElement): CellDump => {
        const cs = getComputedStyle(span);
        return {
          color: cs.color,
          backgroundColor: cs.backgroundColor,
          fontWeight: cs.fontWeight,
          fontStyle: cs.fontStyle,
          textDecorationLine: cs.textDecorationLine,
          textDecorationStyle: cs.textDecorationStyle,
          textDecorationColor: cs.textDecorationColor,
          opacity: cs.opacity,
          visibility: cs.visibility,
          className: span.className,
        };
      };
      // Row order is preserved so result[i] corresponds to manifest row i.
      return Array.from(out.children).map((rowEl) =>
        (Array.from(rowEl.children) as HTMLElement[])
          .filter((s) => (s.textContent ?? "").trim().length > 0)
          .map(dumpSpan),
      );
    });

    // --- Per-code spec analysis. expect.soft so a single run reports EVERY
    // deviation across all 300+ codes, not just the first. ---
    const basicFg = new Map<number, number>(); // SGR code -> rendered 0xRRGGBB
    const idx256Fg = new Map<number, number>(); // 256-index (0..15) -> 0xRRGGBB
    const basicBg = new Map<number, number>(); // SGR code -> 0xRRGGBB

    for (const e of manifest) {
      const spans = dumps[e.row] ?? [];
      const d = spans[0];
      const at = `row ${e.row} ${e.kind} code=${e.code}`;
      expect(d, `${at}: must render a styled span`).toBeTruthy();
      if (!d) {
        continue;
      }
      switch (e.kind) {
        case "attr":
          checkAttr(e.code, d, at);
          break;
        case "attrOff": {
          const off = spans[1];
          expect(off, `${at}: OFF glyph must render`).toBeTruthy();
          if (off) {
            checkAttrOff(e.code, d, off, at);
          }
          break;
        }
        case "defaultColor": {
          const def = spans[1];
          expect(def, `${at}: default glyph must render`).toBeTruthy();
          if (def) {
            checkDefaultColor(e.code, d, def, at);
          }
          break;
        }
        case "ulStyle":
          checkUlStyle(e.code, spans, at);
          break;
        case "basicFg": {
          const got = parseRGB(d.color);
          expect.soft(got, `${at}: fg must be an opaque rgb`).not.toBeNull();
          if (got !== null) {
            basicFg.set(e.code, got);
          }
          break;
        }
        case "basicBg": {
          const got = parseRGB(d.backgroundColor);
          expect.soft(got, `${at}: bg must be an opaque rgb`).not.toBeNull();
          if (got !== null) {
            basicBg.set(e.code, got);
          }
          break;
        }
        case "color256Fg": {
          const got = parseRGB(d.color);
          if (e.code >= 16) {
            // Cube (16-231) + grayscale (232-255): exact standard formula.
            expect
              .soft(got === null ? got : hexStr(got), `${at}: 256-color must equal the spec RGB`)
              .toBe(hexStr(standard256(e.code)));
          } else if (got !== null) {
            // 0-15 are terminal-defined; checked for consistency below.
            idx256Fg.set(e.code, got);
          }
          break;
        }
        case "truecolorFg":
          expect
            .soft(
              parseRGBOrNull(d.color),
              `${at}: truecolor fg must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        case "truecolorBg":
          expect
            .soft(
              parseRGBOrNull(d.backgroundColor),
              `${at}: truecolor bg must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        case "ulColor":
          expect
            .soft(d.textDecorationLine, `${at}: underline must be present`)
            .toContain("underline");
          expect
            .soft(
              parseRGBOrNull(d.textDecorationColor),
              `${at}: underline color must be the exact ${e.r},${e.g},${e.b}`,
            )
            .toBe(rgb(e.r, e.g, e.b));
          break;
        default:
          throw new Error(`unknown manifest kind ${e.kind}`);
      }
    }

    // --- Basic-16 palette. SPEC: the engine's default palette is the published
    // VGA/ANSI 4-bit palette (spec-colors.ts `vga16`, derived independently of
    // wire.go), so pin each slot to its exact RGB — fg 30-37 / 90-97 and bg
    // 40-47 / 100-107. This is the strong assertion a consistency-only check
    // was missing (16 distinct-but-wrong colors used to pass). Then re-assert
    // the ANSI consistency: SGR 38;5;n (n<16) addresses the SAME slot as 3n/9n. ---
    for (let n = 0; n < 8; n++) {
      expect
        .soft(hexOrUndef(basicFg.get(30 + n)), `SGR 3${n} fg == VGA[${n}]`)
        .toBe(hexStr(vga16[n]!));
      expect
        .soft(hexOrUndef(basicFg.get(90 + n)), `SGR 9${n} fg == VGA[${8 + n}]`)
        .toBe(hexStr(vga16[8 + n]!));
      expect
        .soft(hexOrUndef(basicBg.get(40 + n)), `SGR 4${n} bg == VGA[${n}]`)
        .toBe(hexStr(vga16[n]!));
      expect
        .soft(hexOrUndef(basicBg.get(100 + n)), `SGR 10${n} bg == VGA[${8 + n}]`)
        .toBe(hexStr(vga16[8 + n]!));
      assertSameSlot(basicFg.get(30 + n), idx256Fg.get(n), `SGR 3${n} == SGR 38;5;${n}`);
      assertSameSlot(basicFg.get(90 + n), idx256Fg.get(8 + n), `SGR 9${n} == SGR 38;5;${8 + n}`);
    }
    // The 16 base colors must be mutually distinct (a collapsed palette is a bug).
    const distinct = new Set([...basicFg.values()]);
    expect.soft(distinct.size, "the 16 base colors must be mutually distinct").toBe(16);
  });
});

// parseRGBOrNull is parseRGB but typed for the toBe(number) assertions above.
function parseRGBOrNull(s: string): number | null {
  return parseRGB(s);
}

function assertSameSlot(a: number | undefined, b: number | undefined, why: string): void {
  expect.soft(a, `${why}: left slot must render`).not.toBeUndefined();
  expect.soft(b, `${why}: right slot must render`).not.toBeUndefined();
  if (a !== undefined && b !== undefined) {
    expect.soft(hexStr(a), `${why}: same palette slot must render identical RGB`).toBe(hexStr(b));
  }
}

function hexOrUndef(v: number | undefined): string | undefined {
  return v === undefined ? undefined : hexStr(v);
}

// isTransparent reports whether a computed background-color is the default
// (unset) transparent value chromium reports as "rgba(0, 0, 0, 0)".
function isTransparent(s: string): boolean {
  return s === "transparent" || /^rgba\(\s*0,\s*0,\s*0,\s*0\s*\)$/.test(s);
}

// The harness theme (e2e-harness HARNESS): default text #dddee1, default bg #000.
const DEFAULT_FG = 0xdddee1;
const DEFAULT_BG_INVERSE_TEXT = 0x000000; // inverse-on-defaults paints text as --bg

// checkAttrOff asserts the OFF SGR code CLEARED the attribute: the ON glyph
// carries it, the OFF glyph does not. offCode is the SGR that turns it off.
function checkAttrOff(offCode: number, on: CellDump, off: CellDump, at: string): void {
  switch (offCode) {
    case 22: // cancels bold (and faint)
      expect.soft(Number(on.fontWeight), `${at}: ON is bold`).toBeGreaterThanOrEqual(700);
      expect.soft(Number(off.fontWeight), `${at}: 22 clears bold`).toBeLessThan(700);
      break;
    case 23: // not italic
      expect.soft(on.fontStyle, `${at}: ON is italic`).toBe("italic");
      expect.soft(off.fontStyle, `${at}: 23 clears italic`).toBe("normal");
      break;
    case 24: // not underlined
      expect.soft(on.textDecorationLine, `${at}: ON underlined`).toContain("underline");
      expect.soft(off.textDecorationLine, `${at}: 24 clears underline`).not.toContain("underline");
      break;
    case 25: // not blinking
      expect.soft(on.className, `${at}: ON blinks`).toContain("term-blink");
      expect.soft(off.className, `${at}: 25 clears blink`).not.toContain("term-blink");
      break;
    case 27: // not inverse — ON paints text as --bg; OFF restores the default fg
      expect.soft(parseRGB(on.color), `${at}: ON inverse text = bg`).toBe(DEFAULT_BG_INVERSE_TEXT);
      expect.soft(parseRGB(off.color), `${at}: 27 restores default fg`).toBe(DEFAULT_FG);
      break;
    case 28: // reveal (not concealed)
      expect.soft(on.visibility, `${at}: ON hidden`).toBe("hidden");
      expect.soft(off.visibility, `${at}: 28 reveals`).toBe("visible");
      break;
    case 29: // not crossed out
      expect.soft(on.textDecorationLine, `${at}: ON struck`).toContain("line-through");
      expect.soft(off.textDecorationLine, `${at}: 29 clears strike`).not.toContain("line-through");
      break;
    case 55: // not overlined
      expect.soft(on.textDecorationLine, `${at}: ON overlined`).toContain("overline");
      expect.soft(off.textDecorationLine, `${at}: 55 clears overline`).not.toContain("overline");
      break;
    default:
      throw new Error(`unhandled attrOff code ${offCode}`);
  }
}

// checkDefaultColor asserts the channel reverts to its terminal default: the
// set glyph carries the explicit color, the default glyph reverts.
function checkDefaultColor(code: number, set: CellDump, def: CellDump, at: string): void {
  switch (code) {
    case 39: // default fg = theme text color
      expect.soft(parseRGBOrNull(set.color), `${at}: set glyph fg is red`).toBe(vga16[1]!);
      expect.soft(parseRGBOrNull(def.color), `${at}: 39 restores default fg`).toBe(DEFAULT_FG);
      break;
    case 49: // default bg = transparent (unset)
      expect
        .soft(parseRGBOrNull(set.backgroundColor), `${at}: set glyph bg is red`)
        .toBe(vga16[1]!);
      expect
        .soft(isTransparent(def.backgroundColor), `${at}: 49 restores transparent bg`)
        .toBe(true);
      break;
    case 59: // default underline color = currentColor (the glyph's own text color)
      expect
        .soft(parseRGBOrNull(set.textDecorationColor), `${at}: set ul color green`)
        .toBe(rgb(0, 255, 0));
      expect
        .soft(def.textDecorationColor, `${at}: 59 reverts ul color to text color`)
        .toBe(def.color);
      break;
    default:
      throw new Error(`unhandled defaultColor code ${code}`);
  }
}

// checkUlStyle asserts the SGR 4:x colon sub-parameters: 4:2 renders a double
// underline (single glyph); 4:0 clears an underline (ON glyph then OFF glyph).
function checkUlStyle(code: number, spans: CellDump[], at: string): void {
  if (code === 2) {
    const d = spans[0];
    expect(d, `${at}: 4:2 must render`).toBeTruthy();
    if (d) {
      expect.soft(d.textDecorationLine, `${at}: 4:2 is an underline`).toContain("underline");
      expect.soft(d.textDecorationStyle, `${at}: 4:2 is a double underline`).toBe("double");
    }
    return;
  }
  const on = spans[0];
  const off = spans[1];
  expect(on, `${at}: 4 ON glyph`).toBeTruthy();
  expect(off, `${at}: 4:0 OFF glyph`).toBeTruthy();
  if (on) {
    expect.soft(on.textDecorationLine, `${at}: 4 sets underline`).toContain("underline");
  }
  if (off) {
    expect.soft(off.textDecorationLine, `${at}: 4:0 clears underline`).not.toContain("underline");
  }
}

// checkAttr asserts an SGR text-attribute row against the CSS the standard
// prescribes (bold weight, italic style, decoration lines, faint intensity,
// concealment, blink).
function checkAttr(code: number, d: CellDump, at: string): void {
  switch (code) {
    case 1: // bold
      expect.soft(Number(d.fontWeight), `${at}: bold must be >= 700`).toBeGreaterThanOrEqual(700);
      break;
    case 2: // faint / dim — reduced intensity
      expect.soft(Number(d.opacity), `${at}: faint must reduce opacity`).toBeLessThan(1);
      break;
    case 3: // italic
      expect.soft(d.fontStyle, `${at}: italic`).toBe("italic");
      break;
    case 4: // underline
      expect.soft(d.textDecorationLine, `${at}: underline`).toContain("underline");
      break;
    case 5: // blink
    case 6: // rapid blink — the engine aliases it to blink (same class)
      expect.soft(d.className, `${at}: blink must add the blink class`).toContain("term-blink");
      break;
    case 7: // inverse over defaults: fg<->bg swap => text bg-on-fg
      expect.soft(parseRGB(d.color), `${at}: inverse text takes the bg color`).toBe(0x000000);
      expect
        .soft(parseRGB(d.backgroundColor), `${at}: inverse fill takes the fg color`)
        .toBe(0xdddee1);
      break;
    case 8: // conceal / hidden
      expect.soft(d.visibility, `${at}: hidden must be invisible`).toBe("hidden");
      break;
    case 9: // strikethrough
      expect.soft(d.textDecorationLine, `${at}: strike`).toContain("line-through");
      break;
    case 21: // double underline
      expect
        .soft(d.textDecorationLine, `${at}: double underline is an underline`)
        .toContain("underline");
      expect.soft(d.textDecorationStyle, `${at}: double underline style`).toBe("double");
      break;
    case 53: // overline
      expect.soft(d.textDecorationLine, `${at}: overline`).toContain("overline");
      break;
    default:
      throw new Error(`unhandled attr code ${code}`);
  }
}

// WTE is the esbuild IIFE global injected via addScriptTag.
declare const WTE: {
  render: {
    init: (opts: { output: unknown; termWrap: unknown; onCursorMove?: () => void }) => void;
    updateFontMetrics: () => void;
    handleScreen: (msg: unknown) => void;
  };
  decodeWireBinary: (buf: ArrayBuffer) => { type: string } | null;
};
