#!/usr/bin/env python3
"""Regenerate the width tables in vt/width.go from a pinned Unicode version.

Fetches EastAsianWidth.txt and emoji/emoji-data.txt for UNICODE_VERSION from
unicode.org and rewrites the generated region of vt/width.go:

  - wideRanges:  exact coalesced East Asian Width W/F ranges (UAX#11). The UCD
    file itself assigns W to the reserved codepoints of the CJK planes, so the
    plane-2/plane-3 catch-alls survive exact generation.
  - emojiRanges: Emoji_Presentation=Yes minus the regional indicators
    (U+1F1E6..U+1F1FF), which are multi-codepoint flag halves and intentionally
    out of scope (see the width scope note in width.go).

Usage: python3 scripts/gen-width-tables.py   (network access required)

Bumping Unicode: update UNICODE_VERSION, re-run, run `go test ./vt/...`.
"""

import re
import sys
import urllib.request
from pathlib import Path

UNICODE_VERSION = "17.0.0"
UCD_BASE = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd"
WIDTH_GO = Path(__file__).resolve().parent.parent / "vt" / "width.go"

BEGIN = "// BEGIN GENERATED TABLES"
END = "// END GENERATED TABLES"

REGIONAL_INDICATORS = set(range(0x1F1E6, 0x1F1FF + 1))


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8")


def parse_props(text: str, wanted: set[str]) -> set[int]:
    """UCD property file -> set of codepoints whose property is in `wanted`."""
    cps: set[int] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        if len(fields) < 2 or fields[1] not in wanted:
            continue
        rng = fields[0]
        if ".." in rng:
            a, b = rng.split("..")
            cps.update(range(int(a, 16), int(b, 16) + 1))
        else:
            cps.add(int(rng, 16))
    return cps


def coalesce(cps: set[int]) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in sorted(cps):
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def go_table(name: str, ivals: list[tuple[int, int]], comment: str) -> str:
    lines = [comment.rstrip(), f"var {name} = []interval{{"]
    lines.extend(f"\t{{0x{a:04X}, 0x{b:04X}}}," for a, b in ivals)
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    eaw = parse_props(fetch(f"{UCD_BASE}/EastAsianWidth.txt"), {"W", "F"})
    epres = parse_props(fetch(f"{UCD_BASE}/emoji/emoji-data.txt"), {"Emoji_Presentation"})

    wide = coalesce(eaw)
    emoji = coalesce(epres - REGIONAL_INDICATORS)

    header = (
        f"// Code generated by scripts/gen-width-tables.py from UCD {UNICODE_VERSION}"
        " data; DO NOT EDIT BY HAND.\n"
        "// Regenerate: python3 scripts/gen-width-tables.py\n"
    )
    wide_comment = (
        "// wideRanges lists the exact East Asian Wide (W) and Fullwidth (F)\n"
        "// ranges from UAX#11 EastAsianWidth.txt, coalesced. The UCD assigns W to\n"
        "// the reserved codepoints of the CJK planes, so the plane-2/plane-3\n"
        "// catch-alls are preserved by exact generation. Ascending +\n"
        "// non-overlapping for inTable's binary search (guarded by\n"
        "// TestWideRangesSortedNonOverlapping)."
    )
    emoji_comment = (
        "// emojiRanges lists single-codepoint emoji with default emoji\n"
        "// presentation (Unicode Emoji_Presentation=Yes), which render two cells\n"
        "// wide in modern terminals and in the wcwidth model the PTY-side\n"
        "// programs use (go-runewidth), so the engine reserves two cells to stay\n"
        "// in sync (a width-1 mismatch is what clips e.g. \U0001F7E2 U+1F7E2).\n"
        "// Regional-indicator flags (U+1F1E6-1F1FF) and ZWJ / skin-tone /\n"
        "// variation-selector sequences are intentionally excluded: they are\n"
        "// multi-codepoint grapheme clusters, out of scope (see the width scope\n"
        "// note above and the README). Ascending + non-overlapping for inTable's\n"
        "// binary search (guarded by TestEmojiRangesSortedNonOverlapping)."
    )

    region = (
        f"{BEGIN} (do not edit between markers)\n\n"
        + header
        + "\n"
        + go_table("wideRanges", wide, wide_comment)
        + "\n\n"
        + go_table("emojiRanges", emoji, emoji_comment)
        + "\n\n"
        + END
    )

    src = WIDTH_GO.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(src):
        sys.exit(f"markers not found in {WIDTH_GO}")
    WIDTH_GO.write_text(pattern.sub(lambda _: region, src, count=1), encoding="utf-8")
    print(
        f"wrote {WIDTH_GO.name}: wideRanges={len(wide)} intervals, "
        f"emojiRanges={len(emoji)} intervals (UCD {UNICODE_VERSION})"
    )


if __name__ == "__main__":
    main()
