// @vitest-environment happy-dom
//
// Tier 2 — cross-language end-to-end display conformance. The fixture
// ../../render-golden/attributes.bin is the ENGINE's actual wire output for a
// set of real escape sequences (generated by terminal/render_golden_test.go).
// Here the real decoder (decodeWireBinary) and the real renderer (render.ts)
// turn those bytes into DOM, and we assert the SPEC — including exact 256-color
// / truecolor RGB derived from the standard formula, which exercises the Go
// color resolution (colorToWire) all the way to the pixel's CSS. A deviation
// anywhere in engine → wire → decode → render shows up here as a failure.
//
// The row layout is the contract shared with terminal/render_golden_test.go's
// renderGoldenRows; keep the two in lockstep.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { decodeWireBinary } from "./wire-binary.js";
import {
  initHarness,
  renderScreen,
  rowSpans,
  firstTextSpan,
} from "./test-helpers/render-harness.js";
import { standard256, rgb, hex } from "./test-helpers/spec-colors.js";
import type { ScreenMessage } from "./types.js";

const ROW = {
  bold: 0,
  italic: 1,
  underline: 2,
  strikethrough: 3,
  overline: 4,
  color256Red: 5,
  color256Blue: 6,
  color256Gray: 7,
  truecolorFg: 8,
  truecolorBg: 9,
  underlineColor: 10,
  inverseDefault: 11,
  hyperlink: 12,
} as const;

function loadFixture(): ArrayBuffer {
  const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "render-golden");
  const buf = readFileSync(join(dir, "attributes.bin"));
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

describe("cross-language display conformance (real sequences → engine → wire → render)", () => {
  let output: HTMLElement;

  beforeEach(async () => {
    const decoded = decodeWireBinary(loadFixture());
    expect(decoded?.type, "fixture must decode as a screen frame").toBe("screen");
    initHarness();
    output = await renderScreen(decoded as ScreenMessage);
  });

  function styleAt(rowIndex: number): CSSStyleDeclaration {
    const span = firstTextSpan(rowSpans(output, rowIndex));
    expect(span, `row ${rowIndex} must render a glyph span`).toBeDefined();
    return span!.style;
  }

  it("SGR 1 bold renders bold weight", () => {
    expect(["bold", "700"]).toContain(styleAt(ROW.bold).fontWeight);
  });

  it("SGR 3 italic renders italic style", () => {
    expect(styleAt(ROW.italic).fontStyle).toBe("italic");
  });

  it("SGR 4 underline renders an underline", () => {
    expect(styleAt(ROW.underline).textDecoration).toContain("underline");
  });

  it("SGR 9 strikethrough renders a line-through", () => {
    expect(styleAt(ROW.strikethrough).textDecoration).toContain("line-through");
  });

  it("SGR 53 overline renders an overline", () => {
    expect(styleAt(ROW.overline).textDecoration).toContain("overline");
  });

  it("SGR 38;5;196 (256-color cube) resolves to the standard red RGB", () => {
    // Spec cube value for index 196 == #ff0000. Exercises Go color256RGB.
    expect(styleAt(ROW.color256Red).color).toBe(hex(standard256(196)));
  });

  it("SGR 38;5;21 (256-color cube) resolves to the standard blue RGB", () => {
    expect(styleAt(ROW.color256Blue).color).toBe(hex(standard256(21)));
  });

  it("SGR 38;5;244 (256-color grayscale) resolves to the standard gray RGB", () => {
    expect(styleAt(ROW.color256Gray).color).toBe(hex(standard256(244)));
  });

  it("SGR 38;2;255;128;0 (truecolor fg) renders the exact RGB", () => {
    expect(styleAt(ROW.truecolorFg).color).toBe(hex(rgb(255, 128, 0)));
  });

  it("SGR 48;2;0;0;255 (truecolor bg) renders the exact RGB", () => {
    expect(styleAt(ROW.truecolorBg).background).toBe(hex(rgb(0, 0, 255)));
  });

  it("SGR 58 underline color colors the underline with the exact RGB", () => {
    const style = styleAt(ROW.underlineColor);
    expect(style.textDecoration).toContain("underline");
    expect(style.textDecorationColor).toBe(hex(rgb(0, 255, 0)));
  });

  it("SGR 7 inverse over default colors swaps to theme bg-on-fg", () => {
    const style = styleAt(ROW.inverseDefault);
    expect(style.color).toBe("var(--bg)");
    expect(style.background).toBe("var(--text)");
  });

  it("OSC 8 hyperlink renders as an anchor to the URI", () => {
    const anchor = rowSpans(output, ROW.hyperlink).find((s) => s.tagName === "A") as
      HTMLAnchorElement | undefined;
    expect(anchor, "an <a> element must be rendered").toBeDefined();
    expect(anchor!.getAttribute("href")).toBe("https://example.com/x");
  });
});
