// Cross-language wire contract. These are the same bytes the Go encoder
// produced (../../wire-golden/*.bin, generated by terminal/wire_golden_test.go).
// The TS decoder must decode them to the expected messages; if this drifts, the
// Go encoder and TS decoder have diverged. Regenerate the fixtures
// (UPDATE_GOLDEN=1 go test ./terminal/) only for an INTENTIONAL wire change and
// update both halves together.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { decodeWireBinary } from "./wire-binary.js";

const goldenDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "wire-golden");

function load(name: string): ArrayBuffer {
  const buf = readFileSync(join(goldenDir, `${name}.bin`));
  // Return an exact-length ArrayBuffer slice (Node Buffers can share a pool).
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
}

describe("wire golden frames (Go encoder ↔ TS decoder contract)", () => {
  it("decodes the screen frame", () => {
    const m = decodeWireBinary(load("screen"));
    expect(m?.type).toBe("screen");
    if (m?.type !== "screen") {
      return;
    }
    expect(m.base).toBe(100);
    expect(m.cursor).toEqual([1, 2]);
    expect(m.changed).toEqual([0, 2]);
    expect(m.rows[0]?.[0]?.t).toBe("ab");
    expect(m.rows[2]?.[0]?.t).toBe("cd");
    expect(m.cursorStyle).toBe(2);
    expect(m.cursorBlink).toBe(true);
  });

  it("decodes the scroll frame", () => {
    const m = decodeWireBinary(load("scroll"));
    expect(m?.type).toBe("scroll");
    if (m?.type !== "scroll") {
      return;
    }
    expect(m.firstIndex).toBe(50);
    expect(m.lines.length).toBe(2);
    expect(m.lines[0]?.[0]?.t).toBe("h0");
    expect(m.lines[1]?.[0]?.t).toBe("h1");
  });

  it("decodes the resumeAck frame", () => {
    const m = decodeWireBinary(load("resumeack"));
    expect(m?.type).toBe("resumeAck");
    if (m?.type !== "resumeAck") {
      return;
    }
    expect(m.received).toBe(7);
    expect(m.serverEpoch).toBe(1234567890);
    expect(m.committed).toBe(200);
    expect(m.oldestIndex).toBe(10);
    expect(m.serverWireVersion).toBe(4);
    expect(m.ledgerLost).toBe(false);
  });

  it("decodes the ledger-lost resumeAck frame", () => {
    const m = decodeWireBinary(load("resumeack-ledgerlost"));
    expect(m?.type).toBe("resumeAck");
    if (m?.type !== "resumeAck") {
      return;
    }
    expect(m.received).toBe(7);
    expect(m.serverWireVersion).toBe(4);
    expect(m.ledgerLost).toBe(true);
  });

  it("decodes the ackOnly frame", () => {
    const m = decodeWireBinary(load("ackonly"));
    expect(m?.type).toBe("ackOnly");
    if (m?.type !== "ackOnly") {
      return;
    }
    expect(m.inputAck).toBe(42);
  });

  it("decodes the clipboard frame", () => {
    const m = decodeWireBinary(load("clipboard"));
    expect(m?.type).toBe("clipboard");
    if (m?.type !== "clipboard") {
      return;
    }
    expect(m.text).toBe("copy me");
  });

  it("decodes the modes frame", () => {
    const m = decodeWireBinary(load("modes"));
    expect(m?.type).toBe("modes");
    if (m?.type !== "modes") {
      return;
    }
    expect(m.bracketedPaste).toBe(true);
    expect(m.applicationCursor).toBe(false);
    expect(m.mouseSGR).toBe(true);
    expect(m.reverseVideo).toBe(true);
    expect(m.mouseMode).toBe(1002);
    expect(m.keyboardFlags).toBe(1);
  });

  it("decodes the title frame", () => {
    const m = decodeWireBinary(load("title"));
    expect(m?.type).toBe("title");
    if (m?.type !== "title") {
      return;
    }
    expect(m.title).toBe("hello world");
  });

  it("treats the pong frame as a no-op (decodes to null)", () => {
    expect(decodeWireBinary(load("pong"))).toBeNull();
  });
});
