name: Release
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: cplieger/ci/.github/workflows/release.yaml@3015bc1632f52fca3fc2517d82b376f8dbe06a7c # v1
    with:
      target: ts
      working-directory: web
