name: Release
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: cplieger/ci/.github/workflows/release.yaml@c3d6df9d783f0d70aea92c8c1fdba1cfb821a483 # v1
    with:
      target: ts
      working-directory: web
